### ISSUE TITLE
Unabe to close wallet if i choose not to login

### ISSUE THREAD

**Issue by toastedcoins** [casinocoin/casinocoin-wallet#42]
Sometimes I may accidentally open the casinocoin wallet program. If I choose to quit without entering in my wallet password, I am prompted with a message to "Please close the wallet from Tools -> Quit menu".

The only way for the tools menu to appear is to log into my wallet by entering my wallet password. 

Steps to reproduce:

1) Open casinocoin-wallet.exe
2) DO NOT enter wallet password. But try to close the wallet program

You will not be able to close the wallet

**Comment by ajochems** [comment]
You can close the wallet from the login screen clicking the X in the dialog header.
