### ISSUE TITLE
Send amount defaults to 29.999

### ISSUE THREAD

**Issue by ibanezvaio** [casinocoin/casinocoin-wallet#48]
Description
--
Entering = or > 3 numbers (zero does not work) results in a default value of 29.999. Further entered numbers will append to the end

Steps to reproduce
--
Open a wallet
go to Send Coins in the left nav 
select the wallet to send from 
enter Recipient
click into Amount
enter any 3 numbers

Expected results
--
No default value should replace user input

Actual Result
--
Default value of 29.999 replaces user inputted number in Amount field after 3 numbers have been entered

**Comment by nikg-04** [comment]
If you try to enter the amount more than in your account then it shows your account balance by default. If you could share the screenshot, would be more clear to us.

**Comment by ibanezvaio** [comment]
<img width="883" alt="screen shot 2018-07-24 at 21 06 40" src="https://user-images.githubusercontent.com/2853264/43163399-ec5e8d96-8f85-11e8-84f4-8876e4c32393.png">

Achieved by entering 1111 into the Amount input field

**Comment by ajochems** [comment]
Must be you have multiple accounts ... you can not combine coins from multiple accounts into 1 transaction. If the amount entered is higher than the selected source account balance it will be reset to available - fees.
